[package]
name = "zebus"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.0"
prost-types = "0.11.1"
zmq = "0.9.2"
gethostname = "0.2.3"

[dependencies.uuid]
version = "1.2.0"
features = [
    "v4",
    "fast-rng"
]
