[package]
name = "zebus"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.0"
prost-types = "0.11.1"
zmq = { version = "0.9.2", features = ["vendored"] }
gethostname = "0.2.3"
uuid = { version = "1.2.0", features = ["v4", "fast-rng"] }
