[package]
name = "zebus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.0"
prost-types = "0.11.1"
zmq = "0.9.2"
gethostname = "0.2.3"
zebus-macros = { version = "0.1.0", path = "../zebus-macros" }
zebus-core = { version = "0.1.0", path = "../zebus-core" }

[dependencies.uuid]
version = "1.2.0"
features = [
    "v4",
    "fast-rng"
]
